export const dataPacientes = [
  {
    id_paciente: 10,
    priNom_paciente: "Ana",
    segNom_paciente: "Elizabeth",
    priApe_paciente: "Cedeño",
    segApe_paciente: null,
    ced_paciente: "1305343335",
    eda_paciente: 27,
    sex_paciente: "Femenino",
    tel_paciente: "0985542964",
    ema_paciente: "asaxc.1.@gmail.com",
    nomRes_paciente: null,
    parRes_paciente: null,
    telRes_paciente: null,
  },
  {
    id_paciente: 8,
    priNom_paciente: "Ana",
    segNom_paciente: "María",
    priApe_paciente: "Moreno",
    segApe_paciente: "Salgado",
    ced_paciente: "1305458528",
    eda_paciente: 27,
    sex_paciente: "Femenino",
    tel_paciente: "0985542964",
    ema_paciente: "puedeserpa.1.@gmail.com",
    nomRes_paciente: null,
    parRes_paciente: null,
    telRes_paciente: null,
  },
  {
    id_paciente: 1,
    priNom_paciente: "Ronny",
    segNom_paciente: "Bryan",
    priApe_paciente: "Forty",
    segApe_paciente: "Palma",
    ced_paciente: "1315354298",
    eda_paciente: 23,
    sex_paciente: "Masculino",
    tel_paciente: "0985542964",
    ema_paciente: "rbfp90@gmail.com",
    nomRes_paciente: null,
    parRes_paciente: null,
    telRes_paciente: null,
  },
  {
    id_paciente: 2,
    priNom_paciente: "Marcos",
    segNom_paciente: "Antonio",
    priApe_paciente: "Lopes",
    segApe_paciente: "Palma",
    ced_paciente: "1304785425",
    eda_paciente: 27,
    sex_paciente: "Masculino",
    tel_paciente: "0948563212",
    ema_paciente: "marcosAnton@gmail.com",
    nomRes_paciente: null,
    parRes_paciente: null,
    telRes_paciente: null,
  },
  {
    id_paciente: 3,
    priNom_paciente: "Mario",
    segNom_paciente: null,
    priApe_paciente: "Giler",
    segApe_paciente: null,
    ced_paciente: "1386975232",
    eda_paciente: 7,
    sex_paciente: "Masculino",
    tel_paciente: null,
    ema_paciente: "gilermario04@gmail.com",
    nomRes_paciente: "Mario Giler",
    parRes_paciente: "Padre",
    telRes_paciente: "0985445221",
  },
  {
    id_paciente: 4,
    priNom_paciente: "Maria",
    segNom_paciente: "Angelica",
    priApe_paciente: "Forty",
    segApe_paciente: "Benitez",
    ced_paciente: "1305219661",
    eda_paciente: 34,
    sex_paciente: "Femenino",
    tel_paciente: "098465464",
    ema_paciente: "mariaAngelicaForBe@gmail.com",
    nomRes_paciente: null,
    parRes_paciente: null,
    telRes_paciente: null,
  },
  {
    id_paciente: 5,
    priNom_paciente: "Amelia",
    segNom_paciente: null,
    priApe_paciente: "Forty",
    segApe_paciente: "Cedeño",
    ced_paciente: "1315127896",
    eda_paciente: 6,
    sex_paciente: "Femenino",
    tel_paciente: null,
    ema_paciente: null,
    nomRes_paciente: "Juan Carlos Forty",
    parRes_paciente: "Padre",
    telRes_paciente: "0945236547",
  },
  {
    id_paciente: 6,
    priNom_paciente: "Sofía",
    segNom_paciente: null,
    priApe_paciente: "Forty",
    segApe_paciente: null,
    ced_paciente: "1313327855",
    eda_paciente: 4,
    sex_paciente: "Femenino",
    tel_paciente: null,
    ema_paciente: null,
    nomRes_paciente: "Javier Forty Palma",
    parRes_paciente: "Padre",
    telRes_paciente: "0962351424",
  },
  {
    id_paciente: 7,
    priNom_paciente: "Jaynner",
    segNom_paciente: null,
    priApe_paciente: "Forty",
    segApe_paciente: null,
    ced_paciente: "1314783254",
    eda_paciente: 12,
    sex_paciente: "Masculino",
    tel_paciente: null,
    ema_paciente: null,
    nomRes_paciente: "Marianela Cedeño",
    parRes_paciente: "Madre",
    telRes_paciente: "0955215871",
  },
  {
    id_paciente: 76,
    priNom_paciente: "Jaynner",
    segNom_paciente: null,
    priApe_paciente: "Forty",
    segApe_paciente: null,
    ced_paciente: "1314783254",
    eda_paciente: 12,
    sex_paciente: "Masculino",
    tel_paciente: null,
    ema_paciente: null,
    nomRes_paciente: "Marianela Cedeño",
    parRes_paciente: "Madre",
    telRes_paciente: "0955215871",
  },
  {
    id_paciente: 77,
    priNom_paciente: "Jaynner",
    segNom_paciente: null,
    priApe_paciente: "Forty",
    segApe_paciente: null,
    ced_paciente: "1314783254",
    eda_paciente: 12,
    sex_paciente: "Masculino",
    tel_paciente: null,
    ema_paciente: null,
    nomRes_paciente: "Marianela Cedeño",
    parRes_paciente: "Madre",
    telRes_paciente: "0955215871",
  },
  {
    id_paciente: 78,
    priNom_paciente: "Jaynner",
    segNom_paciente: null,
    priApe_paciente: "Forty",
    segApe_paciente: null,
    ced_paciente: "1314783254",
    eda_paciente: 12,
    sex_paciente: "Masculino",
    tel_paciente: null,
    ema_paciente: null,
    nomRes_paciente: "Marianela Cedeño",
    parRes_paciente: "Madre",
    telRes_paciente: "0955215871",
  },
  {
    id_paciente: 79,
    priNom_paciente: "Jaynner",
    segNom_paciente: null,
    priApe_paciente: "Forty",
    segApe_paciente: null,
    ced_paciente: "1314783254",
    eda_paciente: 12,
    sex_paciente: "Masculino",
    tel_paciente: null,
    ema_paciente: null,
    nomRes_paciente: "Marianela Cedeño",
    parRes_paciente: "Madre",
    telRes_paciente: "0955215871",
  },
];
