export const dataCitas = [
  {
    Cuando: "Este mes",
    fecha_cita: "2023-05-15",
    hora_inicio: "08:30",
    hora_fin: "10:30",
    id_paciente: 1,
    Paciente: "Ronny Bryan Forty Palma",
    eda_paciente: 23,
    Telefono: null,
    moti_citaAgen: "Limpieza",
    esta_citaAgen: "Pendiente",
  },
  {
    Cuando: "Este mes",
    fecha_cita: "2023-05-15",
    hora_inicio: "08:31",
    hora_fin: "11:15",
    id_paciente: 6,
    Paciente: "Sofía  Forty ",
    eda_paciente: 4,
    Telefono: "0962351424",
    moti_citaAgen: "Cambio de ligas de brackets",
    esta_citaAgen: "Pendiente",
  },
  {
    Cuando: "Junio",
    fecha_cita: "2023-06-13",
    hora_inicio: "08:30",
    hora_fin: "10:30",
    id_paciente: 7,
    Paciente: "Jaynner  Forty ",
    eda_paciente: 12,
    Telefono: "0955215871",
    moti_citaAgen: "Colocacion de brackets",
    esta_citaAgen: "Pendiente",
  },
  {
    Cuando: "Junio",
    fecha_cita: "2023-06-14",
    hora_inicio: "08:30",
    hora_fin: "10:30",
    id_paciente: 2,
    Paciente: "Marcos Antonio Lopes Palma",
    eda_paciente: 27,
    Telefono: null,
    moti_citaAgen: "Limpieza",
    esta_citaAgen: "Pendiente",
  },
  {
    Cuando: "Diciembre",
    fecha_cita: "2023-12-12",
    hora_inicio: "08:30",
    hora_fin: "10:30",
    id_paciente: 7,
    Paciente: "Jaynner  Forty ",
    eda_paciente: 12,
    Telefono: "0955215871",
    moti_citaAgen:
      "Dolor de muela en el lateral derecho \ndesde hace 3 días, dificultad para masticar a causa del dolor",
    esta_citaAgen: "Pendiente",
  },
];
